name: update-data
run-name: Update source data
on:
  schedule:
    - cron: "11 11 * * *"
  workflow_dispatch:

jobs:
  update-yara-forge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: yara-forge
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Update yara-forge data
        id: update-yara-forge
        run: echo "result=$(python process.py)" >> $GITHUB_OUTPUT

      - name: Check done
        run: |
          if [[ -z "tmp/cleaned-rules.yar" ]]; then
            echo "File not found"
            exit 1
          fi

      - name: Release changes
        if: ${{ ! contains(steps.update-yara-forge.outputs.result, 'No new file found') }}
        uses: softprops/action-gh-release@v0.1.9
        with:
          files: |
            yara-forge/last_file_id
            yara-forge/tmp/cleaned-rules.yar
          name: Release with file ${{ steps.update-yara-forge.outputs.result }}
          tag_name: file-${{ steps.update-yara-forge.outputs.result }}
