name: update-data
run-name: Update source data
on:
  schedule:
    - cron: "11 11 * * *"
  workflow_dispatch:

jobs:
  update-yara-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: yara-rules
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Update yara-rules data
        id: update-yara-rules
        run: echo "result=$(python process.py)" >> $GITHUB_OUTPUT

      - name: Check done
        if: ${{ ! contains(steps.update-yara-rules.outputs.result, 'No new file found') }}
        run: |
          if [[ -z "tmp/*.yar" ]]; then
            echo "File not found"
            exit 1
          fi

      - name: Commit changes
        if: ${{ ! contains(steps.update-yara-rules.outputs.result, 'No new file found') }}
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "Update yara-rules data"
          files: yara-rules/last_file_id yara-rules/elastic_commit_id.txt

      - name: Release changes
        if: ${{ ! contains(steps.update-yara-rules.outputs.result, 'No new file found') }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: yara-rules/last_file_id,yara-rules/tmp/*.yar
          name: Release ${{ steps.update-yara-rules.outputs.result }}
          tag: yara-release-${{ steps.update-yara-rules.outputs.result }}
          makeLatest: true

